metric: COCO
num_classes: 10

# partial labeled COCO, use `SemiCOCODataSet` rather than `COCODataSet`
TrainDataset:
  !SemiCOCODataSet
    image_dir: train/Images
    anno_path: train.json
    dataset_dir: dataset/coco/supervised
    data_fields: ['image', 'gt_bbox', 'gt_class', 'is_crowd']

# partial unlabeled COCO, use `SemiCOCODataSet` rather than `COCODataSet`
UnsupTrainDataset:
  !SemiCOCODataSet
    image_dir: OODSemi
    anno_path: OOD-unlabeled.json
    dataset_dir: dataset/coco/semi_supervised
    data_fields: ['image']
    supervised: False

EvalDataset:
  !COCODataSet
    image_dir: train/Images
    anno_path: train.json
    dataset_dir: dataset/coco/supervised
    allow_empty: true

TestDataset:
  !ImageFolder
    anno_path: annotations/instances_val2017.json # also support txt (like VOC's label_list.txt)
    dataset_dir: dataset/coco # if set, anno_path will be 'dataset_dir/anno_path'
