epoch: 160

LearningRate:
  base_lr: 0.0001
  schedulers:
    - !CosineDecay
      max_epochs: 164
      min_lr_ratio: 0.001 # 0.1
    - !LinearWarmup
      start_factor: 0.001
      epochs: 3


OptimizerBuilder:
  clip_grad_by_norm: 0.1
  regularizer: false
  optimizer:
    type: AdamW
    weight_decay: 0.0001
